/*
 * generated by Xtext
 */
package net.mindengine.galen.ui.contentassist

import net.mindengine.galen.ui.contentassist.AbstractSpecLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SpecLangProposalProvider extends AbstractSpecLangProposalProvider {
}
