/*
* generated by Xtext
*/
package net.mindengine.galen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpecLangStandaloneSetup extends SpecLangStandaloneSetupGenerated{

	public static void doSetup() {
		new SpecLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

