/*
 * generated by Xtext
 */
package net.mindengine.galen;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpecLangRuntimeModule extends net.mindengine.galen.AbstractSpecLangRuntimeModule {

}
