/*
 * generated by Xtext
 */
package net.mindengine.galen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpecLangUiModule extends net.mindengine.galen.ui.AbstractSpecLangUiModule {
	public SpecLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
